FROM node:22-slim AS builder
RUN corepack enable
WORKDIR /app

ARG VITE_CLERK_PUBLISHABLE_KEY=""
ARG VITE_CLERK_PROXY_URL=""
ARG BASE_PATH="/"

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json tsconfig.base.json tsconfig.json ./
COPY artifacts ./artifacts
COPY lib ./lib
COPY scripts ./scripts

RUN pnpm install --frozen-lockfile

ENV NODE_ENV=production
ENV PORT=5173
ENV BASE_PATH=${BASE_PATH}
ENV VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
ENV VITE_CLERK_PROXY_URL=${VITE_CLERK_PROXY_URL}

RUN pnpm --filter @workspace/eltegra-site run build

ENV BASE_PATH=/auditee-tutorial/
RUN pnpm --filter @workspace/auditee-tutorial run build

ENV BASE_PATH=/auditee-deck/
RUN pnpm --filter @workspace/auditee-deck run build


FROM nginx:alpine AS runtime
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/artifacts/eltegra-site/dist/public /usr/share/nginx/html
COPY --from=builder /app/artifacts/auditee-tutorial/dist/public /usr/share/nginx/html/auditee-tutorial
COPY --from=builder /app/artifacts/auditee-deck/dist/public /usr/share/nginx/html/auditee-deck
EXPOSE 80
