import { pool } from "@workspace/db";
import { logger } from "./logger";

type SeedFramework = {
  id: string;
  code: string;
  name: string;
  category: string;
  status: string;
  controls: Array<{ code: string; title: string; description: string }>;
};

const FRAMEWORKS: SeedFramework[] = [
  {
    id: "fw-aspice-4",
    code: "ASPICE 4.0",
    name: "Automotive SPICE 4.0",
    category: "Automotive Process",
    status: "in_progress",
    controls: [
      { code: "ACQ.4", title: "Supplier Monitoring", description: "Monitor the supplier's performance against agreed requirements." },
      { code: "SYS.1", title: "Requirements Elicitation", description: "Establish and maintain stakeholder requirements over the life cycle." },
      { code: "SYS.2", title: "System Requirements Analysis", description: "Transform stakeholder requirements into a set of system requirements." },
      { code: "SYS.3", title: "System Architectural Design", description: "Establish a system architectural design and identify which system requirements are allocated to which elements." },
      { code: "SYS.4", title: "System Integration and Integration Verification", description: "Integrate system items and verify integration against the system architectural design." },
      { code: "SYS.5", title: "System Verification", description: "Verify the integrated system against the system requirements." },
      { code: "SWE.1", title: "Software Requirements Analysis", description: "Establish a structured set of software requirements consistent with system requirements." },
      { code: "SWE.2", title: "Software Architectural Design", description: "Establish a software architectural design and allocate requirements to software components." },
      { code: "SWE.3", title: "Software Detailed Design and Unit Construction", description: "Provide a detailed design for the software components and produce verified software units." },
      { code: "SWE.4", title: "Software Unit Verification", description: "Verify software units against the software detailed design and unit verification criteria." },
      { code: "SWE.5", title: "Software Component Verification and Integration Verification", description: "Verify software components and the integration of software components against the architectural design." },
      { code: "SWE.6", title: "Software Verification", description: "Verify the integrated software against the software requirements." },
      { code: "VAL.1", title: "Validation", description: "Provide objective evidence that the system, when used in its intended operational environment, satisfies stakeholder needs." },
      { code: "SUP.1", title: "Quality Assurance", description: "Provide independent and objective assurance that work products and processes comply with predefined provisions and plans." },
      { code: "SUP.8", title: "Configuration Management", description: "Establish and maintain the integrity of all work products of a process or project." },
      { code: "SUP.9", title: "Problem Resolution Management", description: "Identify, analyze, manage and control problems to resolution." },
      { code: "SUP.10", title: "Change Request Management", description: "Manage all change requests in a systematic and traceable way." },
      { code: "MAN.3", title: "Project Management", description: "Identify, establish, and control the activities and resources necessary for a project to produce a product." },
      { code: "MAN.5", title: "Risk Management", description: "Continuously identify, analyze, treat and monitor risks." },
      { code: "MAN.6", title: "Measurement", description: "Collect and analyze data relating to products, processes and projects to support effective management." },
    ],
  },
  {
    id: "fw-cmmi-3",
    code: "CMMI 3.0",
    name: "CMMI for Development v3.0",
    category: "Process Maturity",
    status: "in_progress",
    controls: [
      { code: "GOV", title: "Governance", description: "Provide guidance to senior management on their role in sponsoring and steering process activities." },
      { code: "II", title: "Implementation Infrastructure", description: "Ensure processes important to the organization are persistently and habitually used and improved." },
      { code: "EST", title: "Estimating", description: "Estimate the size, effort, duration, resources, and cost of the work and resources required to develop, acquire, or deliver the solution." },
      { code: "PLAN", title: "Planning", description: "Develop plans to describe what is needed to accomplish the work within the standards and constraints of the organization." },
      { code: "MC", title: "Monitor and Control", description: "Provide an understanding of the project progress so appropriate corrective actions can be taken when performance deviates significantly from plans." },
      { code: "SAM", title: "Supplier Agreement Management", description: "Manage the acquisition of products and services from suppliers." },
      { code: "RDM", title: "Requirements Development and Management", description: "Elicit requirements, ensure common understanding by stakeholders, and align requirements, plans, and work products." },
      { code: "TS", title: "Technical Solution", description: "Design and build solutions (products, services, and solution components) that meet customer requirements." },
      { code: "PI", title: "Product Integration", description: "Integrate and deliver the solution that addresses functionality and quality requirements." },
      { code: "VV", title: "Verification and Validation", description: "Confirm that the solution and solution components meet their requirements and validate that they fulfill their intended use." },
      { code: "PR", title: "Peer Reviews", description: "Identify and address work product issues through reviews by the producer's peers or subject matter experts." },
      { code: "RSK", title: "Risk and Opportunity Management", description: "Identify, record, analyze, and manage potential risks or opportunities." },
      { code: "CM", title: "Configuration Management", description: "Manage the integrity of work products using configuration identification, control, status accounting, and audits." },
      { code: "PQA", title: "Process Quality Assurance", description: "Verify and enable improvement of the quality of the performed processes and resulting work products." },
      { code: "CAR", title: "Causal Analysis and Resolution", description: "Identify causes of selected outcomes and take action to either prevent recurrence of undesirable outcomes or ensure recurrence of positive outcomes." },
      { code: "DAR", title: "Decision Analysis and Resolution", description: "Make and record decisions using a recorded process that analyzes alternatives." },
      { code: "OT", title: "Organizational Training", description: "Develop the competence of people to perform their roles effectively and efficiently." },
      { code: "PAD", title: "Process Asset Development", description: "Develop and keep updated the process assets necessary to perform the work." },
      { code: "MPM", title: "Managing Performance and Measurement", description: "Manage performance using measurement and analysis to achieve business objectives." },
    ],
  },

  // ─── Cybersecurity ─────────────────────────────────────────────────────
  {
    // Reuse the seed's ID so this upserts into the existing row instead of
    // creating a duplicate "ISO 27001" / "ISO/IEC 27001" pair.
    id: "fw-iso",
    code: "ISO/IEC 27001",
    name: "ISO/IEC 27001:2022 — Information Security Management Systems",
    category: "Information Security",
    status: "in_progress",
    controls: [
      { code: "A.5.1", title: "Policies for information security", description: "Information security policy and topic-specific policies shall be defined, approved, published, communicated and reviewed." },
      { code: "A.5.7", title: "Threat intelligence", description: "Information relating to information security threats shall be collected and analysed." },
      { code: "A.5.15", title: "Access control", description: "Rules to control physical and logical access to information and other associated assets shall be established and implemented." },
      { code: "A.5.23", title: "Information security for use of cloud services", description: "Processes for acquisition, use, management and exit from cloud services shall be established in line with the organization's requirements." },
      { code: "A.5.24", title: "Information security incident management planning and preparation", description: "The organization shall plan and prepare for managing information security incidents by defining roles, responsibilities and processes." },
      { code: "A.6.3", title: "Information security awareness, education and training", description: "Personnel and relevant interested parties shall receive appropriate awareness, education and training on the organization's information security policy." },
      { code: "A.7.4", title: "Physical security monitoring", description: "Premises shall be continuously monitored for unauthorised physical access." },
      { code: "A.8.2", title: "Privileged access rights", description: "The allocation and use of privileged access rights shall be restricted and managed." },
      { code: "A.8.7", title: "Protection against malware", description: "Protection against malware shall be implemented and supported by appropriate user awareness." },
      { code: "A.8.8", title: "Management of technical vulnerabilities", description: "Information about technical vulnerabilities of information systems shall be obtained, the organization's exposure evaluated and appropriate measures taken." },
      { code: "A.8.16", title: "Monitoring activities", description: "Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken to evaluate potential information security incidents." },
      { code: "A.8.24", title: "Use of cryptography", description: "Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented." },
      { code: "A.8.28", title: "Secure coding", description: "Secure coding principles shall be applied to software development." },
    ],
  },
  {
    id: "fw-iso-27002",
    code: "ISO/IEC 27002",
    name: "ISO/IEC 27002:2022 — Information Security Controls",
    category: "Information Security",
    status: "in_progress",
    controls: [
      { code: "5.10", title: "Acceptable use of information and other assets", description: "Rules for the acceptable use and procedures for handling information and other associated assets shall be identified, documented and implemented." },
      { code: "5.12", title: "Classification of information", description: "Information shall be classified according to the information security needs of the organization based on confidentiality, integrity, availability and relevant interested party requirements." },
      { code: "5.14", title: "Information transfer", description: "Information transfer rules, procedures or agreements shall be in place for all types of transfer facilities within and outside the organization." },
      { code: "5.30", title: "ICT readiness for business continuity", description: "ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements." },
      { code: "6.7", title: "Remote working", description: "Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organization's premises." },
      { code: "8.9", title: "Configuration management", description: "Configurations, including security configurations, of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed." },
      { code: "8.12", title: "Data leakage prevention", description: "Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit sensitive information." },
      { code: "8.15", title: "Logging", description: "Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed." },
      { code: "8.23", title: "Web filtering", description: "Access to external websites shall be managed to reduce exposure to malicious content." },
      { code: "8.25", title: "Secure development life cycle", description: "Rules for the secure development of software and systems shall be established and applied." },
      { code: "8.26", title: "Application security requirements", description: "Information security requirements shall be identified, specified and approved when developing or acquiring applications." },
      { code: "8.29", title: "Security testing in development and acceptance", description: "Security testing processes shall be defined and implemented in the development life cycle." },
    ],
  },
  {
    id: "fw-nist-csf",
    code: "NIST CSF 2.0",
    name: "NIST Cybersecurity Framework 2.0",
    category: "Cybersecurity",
    status: "in_progress",
    controls: [
      { code: "GV.OC", title: "Organizational Context", description: "The circumstances — mission, stakeholder expectations, dependencies, and legal, regulatory, and contractual requirements — surrounding the organization's cybersecurity risk management decisions are understood." },
      { code: "GV.RM", title: "Risk Management Strategy", description: "The organization's priorities, constraints, risk tolerance and assumptions are established, communicated, and used to support operational risk decisions." },
      { code: "GV.SC", title: "Cybersecurity Supply Chain Risk Management", description: "Cyber supply chain risk management processes are identified, established, managed, monitored, and improved." },
      { code: "ID.AM", title: "Asset Management", description: "Assets (data, hardware, software, systems, facilities, services, people) that enable the organization to achieve business purposes are identified and managed consistent with their relative importance to organizational objectives and the organization's risk strategy." },
      { code: "ID.RA", title: "Risk Assessment", description: "The organization understands the cybersecurity risk to organizational operations, assets and individuals." },
      { code: "PR.AA", title: "Identity Management, Authentication, and Access Control", description: "Access to physical and logical assets is limited to authorized users, services and hardware, and managed commensurate with the assessed risk of unauthorized access." },
      { code: "PR.DS", title: "Data Security", description: "Data is managed consistent with the organization's risk strategy to protect the confidentiality, integrity and availability of information." },
      { code: "PR.PS", title: "Platform Security", description: "The hardware, software and services of physical and virtual platforms are managed consistent with the organization's risk strategy." },
      { code: "DE.CM", title: "Continuous Monitoring", description: "Assets are monitored to find anomalies, indicators of compromise, and other potentially adverse events." },
      { code: "DE.AE", title: "Adverse Event Analysis", description: "Anomalies, indicators of compromise, and other potentially adverse events are analyzed to characterize the events and detect cybersecurity incidents." },
      { code: "RS.MA", title: "Incident Management", description: "Responses to detected cybersecurity incidents are managed." },
      { code: "RS.AN", title: "Incident Analysis", description: "Investigations are conducted to ensure effective response and support forensics and recovery activities." },
      { code: "RC.RP", title: "Incident Recovery Plan Execution", description: "Restoration activities are performed to ensure operational availability of systems and services affected by cybersecurity incidents." },
      { code: "RC.CO", title: "Incident Recovery Communication", description: "Restoration activities are coordinated with internal and external parties." },
    ],
  },
  {
    id: "fw-aspice-cyber",
    code: "ASPICE Cybersecurity 2.0",
    name: "Automotive SPICE for Cybersecurity v2.0 (2025)",
    category: "Automotive Cybersecurity",
    status: "in_progress",
    controls: [
      { code: "SEC.1", title: "Cybersecurity Requirements Elicitation", description: "Identify, elicit and document cybersecurity requirements derived from threat analysis and risk assessment (TARA)." },
      { code: "SEC.2", title: "Cybersecurity Implementation", description: "Implement cybersecurity controls in the architecture, design and code consistent with the elicited cybersecurity requirements." },
      { code: "SEC.3", title: "Risk Treatment Verification", description: "Verify that cybersecurity risks identified in TARA are appropriately treated and that residual risk is acceptable." },
      { code: "SEC.4", title: "Cybersecurity Validation", description: "Validate that the integrated system, in its operational environment, withstands the threats identified in the TARA and meets cybersecurity goals." },
      { code: "ACQ.2", title: "Supplier Cybersecurity Qualification", description: "Suppliers shall demonstrate cybersecurity capability appropriate to the items they deliver, including TARA, secure development and incident response." },
      { code: "MAN.7", title: "Cybersecurity Risk Management", description: "Continuously identify, analyze, treat and monitor cybersecurity risks across the product lifecycle." },
      { code: "SUP.11", title: "Cybersecurity Incident Response", description: "Establish a process to detect, triage, respond to and report cybersecurity incidents affecting fielded vehicles." },
      { code: "SUP.12", title: "Cryptographic Asset Management", description: "Manage cryptographic assets (keys, certificates, hardware roots of trust) over their lifecycle, including provisioning, rotation and revocation." },
    ],
  },
  {
    id: "fw-iec-62443",
    code: "IEC 62443",
    name: "IEC 62443 — Industrial Automation & Control Systems Security",
    category: "Industrial Cybersecurity",
    status: "in_progress",
    controls: [
      { code: "FR1", title: "Identification & Authentication Control (IAC)", description: "All users (humans, software processes and devices) shall be identified and authenticated before being granted access to the IACS." },
      { code: "FR2", title: "Use Control (UC)", description: "Authenticated users shall be enforced to use only the privileges they have been assigned, on the assets they are authorized to use." },
      { code: "FR3", title: "System Integrity (SI)", description: "Ensure the integrity of the IACS to prevent unauthorized manipulation of the control system, communications, software and configuration." },
      { code: "FR4", title: "Data Confidentiality (DC)", description: "Ensure the confidentiality of information on communication channels and in data repositories to prevent unauthorized disclosure." },
      { code: "FR5", title: "Restricted Data Flow (RDF)", description: "Segment the control system network via zones and conduits to limit unnecessary data flow between zones." },
      { code: "FR6", title: "Timely Response to Events (TRE)", description: "Respond to security violations by notifying the proper authority, reporting evidence of the violation and taking timely corrective action." },
      { code: "FR7", title: "Resource Availability (RA)", description: "Ensure the availability of the control system against the degradation or denial of essential services." },
      { code: "SR2.8", title: "Auditable Events", description: "The control system shall provide the capability to generate audit records of security-relevant events, including changes to audit-record settings and security functions." },
      { code: "SR3.4", title: "Software & Information Integrity", description: "Verify the integrity of software and information at startup and during operation, and respond to integrity violations." },
      { code: "SR7.6", title: "Network & Security Configuration Settings", description: "Configure network and security settings according to recommended hardening guides and verify the as-implemented state." },
    ],
  },

  // ─── Functional Safety ─────────────────────────────────────────────────
  {
    id: "fw-iso-26262",
    code: "ISO 26262",
    name: "ISO 26262 — Road Vehicles Functional Safety",
    category: "Automotive Functional Safety",
    status: "in_progress",
    controls: [
      { code: "Pt2-6", title: "Safety Management During Concept & Development", description: "Plan, coordinate and document the safety activities during the concept phase and product development; assign roles and responsibilities." },
      { code: "Pt3-6", title: "Hazard Analysis & Risk Assessment (HARA)", description: "Identify and categorize hazards triggered by malfunctioning behaviour and formulate the safety goals with associated ASIL." },
      { code: "Pt3-7", title: "Functional Safety Concept", description: "Derive the functional safety concept that describes the functional safety requirements with their allocation to system elements." },
      { code: "Pt4-6", title: "Technical Safety Concept", description: "Specify the technical safety requirements and the system architectural design that implements the functional safety concept." },
      { code: "Pt4-9", title: "Safety Validation", description: "Provide evidence that the safety goals are correct, complete and fully achieved at the vehicle level." },
      { code: "Pt6-7", title: "Software Architectural Design", description: "Develop a software architectural design that implements the software safety requirements with adequate freedom from interference." },
      { code: "Pt6-9", title: "Software Unit Verification", description: "Verify that software units fulfil the unit design specification, do not contain undesired functionality, and meet coverage targets appropriate to the ASIL." },
      { code: "Pt6-10", title: "Software Integration & Verification", description: "Integrate the software components and verify that the embedded software fulfils the software safety requirements." },
      { code: "Pt8-6", title: "Specification & Management of Safety Requirements", description: "Specify safety requirements with attributes (ASIL, allocation, traceability) and manage them throughout the lifecycle." },
      { code: "Pt8-7", title: "Configuration Management", description: "Apply configuration management to all safety-related work products to ensure their integrity and reproducibility." },
      { code: "Pt8-9", title: "Verification", description: "Define and execute verification activities (reviews, analyses, tests) appropriate to the ASIL of the work product." },
      { code: "Pt9-5", title: "Requirements Decomposition with Respect to ASIL", description: "If ASIL decomposition is applied, demonstrate sufficient independence between the decomposed requirements and their implementations." },
    ],
  },
  {
    id: "fw-iec-61508",
    code: "IEC 61508",
    name: "IEC 61508 — Functional Safety of E/E/PE Safety-Related Systems",
    category: "Functional Safety",
    status: "in_progress",
    controls: [
      { code: "Pt1-7.1", title: "Overall Safety Lifecycle", description: "Define and follow an overall safety lifecycle, with clear inputs, outputs and verification activities for each phase." },
      { code: "Pt1-7.4", title: "Hazard & Risk Analysis", description: "Determine hazards, hazardous events and hazardous situations; estimate the risk associated with each and identify the safety functions required." },
      { code: "Pt1-7.5", title: "Overall Safety Requirements & Allocation", description: "Specify the overall safety requirements (functional and integrity) and allocate them to designated E/E/PE safety-related systems." },
      { code: "Pt1-7.7", title: "Safety Validation Planning", description: "Plan the validation of the overall safety requirements, including the validation of safety functions and the SIL achieved." },
      { code: "Pt2-7.4", title: "E/E/PE System Design Requirements", description: "Specify the requirements for the design of the E/E/PE system to meet the safety functions and the required safety integrity level (SIL)." },
      { code: "Pt2-7.6", title: "Hardware Safety Integrity", description: "Demonstrate that the hardware safety integrity (architectural constraints and probability of failure) meets the required SIL." },
      { code: "Pt3-7.2", title: "Software Safety Lifecycle Requirements", description: "Apply a software safety lifecycle commensurate with the SIL, including planning, design, coding, verification and validation activities." },
      { code: "Pt3-7.4", title: "Software Architecture Design", description: "Specify a software architecture that meets the software safety requirements and supports the techniques and measures appropriate to the SIL." },
      { code: "Pt3-7.7", title: "Software Module Testing & Integration", description: "Plan, execute and document module testing and integration to demonstrate that the software meets the safety requirements." },
      { code: "Pt7", title: "Techniques & Measures", description: "Select and justify the techniques and measures used in each lifecycle phase from the recommendations in Part 7 against the target SIL." },
    ],
  },
  {
    id: "fw-iec-62304",
    code: "IEC 62304",
    name: "IEC 62304 — Medical Device Software Lifecycle",
    category: "Medical Device Safety",
    status: "in_progress",
    controls: [
      { code: "4.3", title: "Software Safety Classification", description: "Assign a software safety class (A, B or C) to each software system based on possible effects on the patient, operator or other people resulting from a hazard." },
      { code: "5.1", title: "Software Development Planning", description: "Establish a software development plan covering processes, deliverables, tools, configuration management and verification activities." },
      { code: "5.2", title: "Software Requirements Analysis", description: "Define and document software requirements derived from the system requirements and risk control measures." },
      { code: "5.3", title: "Software Architectural Design", description: "Develop and document software architecture that implements the software requirements, with explicit handling of SOUP (software of unknown provenance)." },
      { code: "5.5", title: "Software Unit Implementation & Verification", description: "Implement each software unit and verify it against the unit acceptance criteria appropriate for the safety class." },
      { code: "5.6", title: "Software Integration & Integration Testing", description: "Integrate the software units and verify the integrated software against the integration test plan." },
      { code: "5.7", title: "Software System Testing", description: "Verify that the integrated software system meets the software requirements." },
      { code: "5.8", title: "Software Release", description: "Document and version-control the released software, including known anomalies and associated risk evaluation." },
      { code: "6", title: "Software Maintenance Process", description: "Establish a maintenance process for received feedback, problem analysis, modification implementation and re-release." },
      { code: "7", title: "Software Risk Management Process", description: "Apply the risk management process of ISO 14971 to identify hazardous situations contributed to by software and define risk control measures." },
      { code: "8", title: "Software Configuration Management", description: "Identify configuration items, control changes to them and report on their status throughout the lifecycle." },
      { code: "9", title: "Software Problem Resolution Process", description: "Prepare problem reports for each problem detected, investigate and resolve them, and verify the resolution." },
    ],
  },
  {
    id: "fw-do-178c",
    code: "DO-178C",
    name: "DO-178C — Software Considerations in Airborne Systems",
    category: "Avionics Safety",
    status: "in_progress",
    controls: [
      { code: "4", title: "Software Planning Process", description: "Produce a Plan for Software Aspects of Certification (PSAC), Software Development Plan, Verification Plan, Configuration Management Plan and Quality Assurance Plan." },
      { code: "5.1", title: "Software Requirements Process", description: "Develop high-level software requirements that satisfy the system requirements allocated to software, with traceability to the system requirements." },
      { code: "5.2", title: "Software Design Process", description: "Develop low-level software requirements and software architecture from the high-level requirements, with traceability between levels." },
      { code: "5.3", title: "Software Coding Process", description: "Implement Source Code consistent with the software design and the coding standards defined in the planning process." },
      { code: "5.4", title: "Integration Process", description: "Integrate the Source Code with the target hardware and produce the Executable Object Code." },
      { code: "6.3", title: "Reviews & Analyses of the Requirements", description: "Conduct reviews and analyses of the software requirements, design and code to detect and report errors." },
      { code: "6.4", title: "Software Testing Process", description: "Perform requirements-based test case selection and execute hardware/software integration, software integration and low-level tests." },
      { code: "6.4.4", title: "Structural Coverage Analysis", description: "Analyse the structural coverage achieved by requirements-based testing (statement, decision, MC/DC) appropriate to the software level (DAL A–E)." },
      { code: "7", title: "Software Configuration Management Process", description: "Establish a Software Configuration Management process for control, identification, baselines, problem reporting, archive and release." },
      { code: "8", title: "Software Quality Assurance Process", description: "Provide assurance that the software lifecycle processes produce software that conforms to its requirements and that the processes are followed." },
      { code: "11.20", title: "Software Configuration Index (SCI)", description: "Identify the configuration of the software product including all software lifecycle data and the environment used to develop, verify and produce the software." },
      { code: "12.2", title: "Tool Qualification", description: "Qualify any software tool whose output is part of airborne software and is not verified, or that automates a verification activity such that the activity is eliminated, reduced or automated." },
    ],
  },
  {
    id: "fw-iec-60601",
    code: "IEC 60601",
    name: "IEC 60601 series — Medical Electrical Equipment, Essential Safety and Performance",
    category: "Medical Device Safety",
    status: "in_progress",
    controls: [
      { code: "60601-1 Cl. 4", title: "General Requirements", description: "Apply general requirements for basic safety and essential performance, including risk management file integration per ISO 14971." },
      { code: "60601-1 Cl. 7", title: "ME Equipment Identification, Marking and Documents", description: "Provide markings, accompanying documents, instructions for use and technical description per the standard." },
      { code: "60601-1 Cl. 8", title: "Protection Against Electrical Hazards", description: "Implement means of operator and patient protection (MOOP/MOPP), creepage/clearance and dielectric strength requirements." },
      { code: "60601-1 Cl. 9", title: "Protection Against Mechanical Hazards", description: "Mitigate mechanical hazards: moving parts, instability, expelled parts, pressure vessels and acoustic energy." },
      { code: "60601-1 Cl. 11", title: "Protection Against Excessive Temperatures and Other Hazards", description: "Limit temperatures of applied parts and accessible surfaces; address fire, fluid ingress and biocompatibility hazards." },
      { code: "60601-1 Cl. 12", title: "Accuracy of Controls and Protection Against Hazardous Outputs", description: "Demonstrate accuracy of controls, instruments, and protection against hazardous outputs and operating data." },
      { code: "60601-1 Cl. 13", title: "Hazardous Situations and Fault Conditions", description: "Demonstrate that single-fault conditions do not result in unacceptable risk to patient or operator." },
      { code: "60601-1 Cl. 14", title: "Programmable Electrical Medical Systems (PEMS)", description: "Apply a PEMS development life cycle including risk management, requirements specification, architecture, design, V&V and modification (links to IEC 62304)." },
      { code: "60601-1 Cl. 15", title: "Construction of ME Equipment", description: "Apply construction requirements including components, mains parts, wiring, batteries and indicators." },
      { code: "60601-1 Cl. 17", title: "Electromagnetic Compatibility (per IEC 60601-1-2)", description: "Demonstrate EMC compliance: emissions, immunity, and risk-based EMC test plan including reasonably foreseeable use environment." },
      { code: "60601-1-6", title: "Usability (links to IEC 62366-1)", description: "Apply the usability engineering process and reference IEC 62366-1 deliverables in the device file." },
      { code: "60601-1-8", title: "Alarm Systems", description: "Apply alarm system requirements: alarm conditions, priorities, signals, logging and inactivation states." },
      { code: "60601-1-9", title: "Environmentally Conscious Design", description: "Address environmental aspects across the life cycle (materials, energy, packaging, end-of-life)." },
    ],
  },
  {
    id: "fw-iso-13485",
    code: "ISO 13485",
    name: "ISO 13485:2016 — Medical Devices Quality Management Systems",
    category: "Medical Device QMS",
    status: "in_progress",
    controls: [
      { code: "4.1", title: "General QMS Requirements", description: "Establish, document, implement and maintain a QMS appropriate to the role of the organization in the medical device life cycle." },
      { code: "4.2", title: "Documentation Requirements", description: "Maintain a Medical Device File for each device family with specifications, processes, labelling, packaging, installation and servicing procedures." },
      { code: "5.5", title: "Responsibility, Authority and Communication", description: "Define organizational structure, appoint a management representative and ensure regulatory communication processes." },
      { code: "6.2", title: "Human Resources", description: "Determine competence, provide training and maintain training records for personnel performing work affecting product quality." },
      { code: "7.1", title: "Planning of Product Realization", description: "Plan and develop the processes needed for product realization, including risk management throughout product realization." },
      { code: "7.2", title: "Customer-Related Processes", description: "Determine and review requirements related to the device, including regulatory requirements and user training needs." },
      { code: "7.3", title: "Design and Development", description: "Establish design controls including planning, inputs, outputs, review, verification, validation, transfer, change control and design history file." },
      { code: "7.4", title: "Purchasing", description: "Ensure purchased product conforms to specified purchasing information; evaluate and select suppliers based on ability to meet requirements." },
      { code: "7.5", title: "Production and Service Provision", description: "Plan and carry out production under controlled conditions including process validation for processes whose output cannot be verified." },
      { code: "7.6", title: "Control of Monitoring and Measuring Equipment", description: "Determine measurements to be made, calibrate equipment, and protect from adjustments that would invalidate measurement results." },
      { code: "8.2.1", title: "Feedback", description: "Establish documented procedures to gather feedback from production and post-production activities; feedback is an input into risk management and product realisation." },
      { code: "8.2.2", title: "Complaint Handling", description: "Establish documented procedures for timely complaint handling: receipt, investigation, evaluation against MDR-reportability, corrective action and records." },
      { code: "8.2.6", title: "Monitoring and Measurement of Product", description: "Monitor and measure characteristics of the device to verify product requirements have been met; maintain records of release authority." },
      { code: "8.3", title: "Control of Nonconforming Product", description: "Identify and control nonconforming product to prevent unintended use or delivery; document concessions and rework." },
      { code: "8.5.2", title: "Corrective Action (CAPA)", description: "Take action to eliminate the cause of nonconformities to prevent recurrence; document the CAPA process." },
      { code: "8.5.3", title: "Preventive Action", description: "Determine action to eliminate the causes of potential nonconformities to prevent their occurrence." },
    ],
  },
  {
    id: "fw-iso-14971",
    code: "ISO 14971",
    name: "ISO 14971:2019 — Application of Risk Management to Medical Devices",
    category: "Medical Device Risk Management",
    status: "in_progress",
    controls: [
      { code: "4.1", title: "Risk Management Process", description: "Establish, document and maintain a continuous risk management process throughout the life cycle of the medical device." },
      { code: "4.2", title: "Management Responsibilities", description: "Top management must commit resources, define and document the policy for determining acceptable risk, and review risk management activities." },
      { code: "4.3", title: "Competence of Personnel", description: "Persons performing risk management tasks shall be qualified on the basis of education, training, skills and experience appropriate to the tasks assigned." },
      { code: "4.4", title: "Risk Management Plan", description: "Establish and document a risk management plan including scope, allocation of responsibilities, review requirements, criteria for risk acceptability and verification activities." },
      { code: "4.5", title: "Risk Management File", description: "Establish and maintain a risk management file providing traceability for each identified hazard to: risk analysis, risk evaluation, risk control implementation/verification and residual-risk acceptability evaluation." },
      { code: "5", title: "Risk Analysis", description: "Identify intended use and reasonably foreseeable misuse, identify characteristics related to safety, identify hazards and hazardous situations, and estimate the risks for each hazardous situation." },
      { code: "6", title: "Risk Evaluation", description: "Decide for each hazardous situation whether risk reduction is required using the criteria defined in the risk management plan." },
      { code: "7.1", title: "Risk Control Option Analysis", description: "Determine risk control measures using the priority order: (a) inherently safe design, (b) protective measures, (c) information for safety." },
      { code: "7.4", title: "Risk Control Verification", description: "Verify implementation and effectiveness of each risk control measure; record results in the risk management file." },
      { code: "7.6", title: "Risk/Benefit Analysis", description: "When residual risk is judged unacceptable, conduct a benefit-risk analysis of the residual risk against the medical benefit of the intended use." },
      { code: "8", title: "Evaluation of Overall Residual Risk", description: "After all risk control measures have been implemented and verified, evaluate the overall residual risk against the criteria in the risk management plan." },
      { code: "9", title: "Risk Management Review", description: "Before commercial distribution, review execution of the risk management plan; document the review in a risk management report." },
      { code: "10", title: "Production and Post-Production Activities", description: "Establish a system to collect and review information about the device in production and post-production phases and feed it back into the risk management process." },
    ],
  },
  {
    id: "fw-iec-62366",
    code: "IEC 62366",
    name: "IEC 62366-1:2015 — Application of Usability Engineering to Medical Devices",
    category: "Medical Device Usability",
    status: "in_progress",
    controls: [
      { code: "5.1", title: "Use Specification", description: "Prepare a use specification including intended medical indication, intended patient population, intended part of the body, intended user profile, intended use environment and operating principle." },
      { code: "5.2", title: "User Interface Characteristics Related to Safety and Use Errors", description: "Identify user interface characteristics related to safety and the potential for use errors that could result in harm." },
      { code: "5.3", title: "Known and Foreseeable Hazards and Hazardous Situations", description: "Identify known or foreseeable hazards and hazardous situations related to the user interface and reasonably foreseeable misuse." },
      { code: "5.4", title: "Hazard-Related Use Scenarios", description: "Identify and describe hazard-related use scenarios for which the consequence could be harm." },
      { code: "5.5", title: "Selection of Hazard-Related Use Scenarios for Summative Evaluation", description: "Select the subset of hazard-related use scenarios to be included in summative evaluation of usability." },
      { code: "5.6", title: "User Interface Specification", description: "Establish the user interface specification consistent with the use specification and the identified hazard-related use scenarios." },
      { code: "5.7", title: "User Interface Evaluation Plan", description: "Establish and maintain a user interface evaluation plan covering both formative and summative evaluation activities." },
      { code: "5.8", title: "User Interface Design, Implementation and Formative Evaluation", description: "Iteratively design, implement and formatively evaluate the user interface against the user interface specification." },
      { code: "5.9", title: "Summative Evaluation of the User Interface", description: "Perform summative evaluation of the user interface to demonstrate safe use; document protocol, results and any residual usability issues." },
      { code: "6", title: "User Interface of Unknown Provenance (UOUP)", description: "Apply the alternate process for evaluating the user interface of unknown provenance when reusing existing designs without full usability records." },
    ],
  },
  {
    id: "fw-iso-14155",
    code: "ISO 14155",
    name: "ISO 14155:2020 — Clinical Investigation of Medical Devices for Human Subjects",
    category: "Medical Device Clinical Investigation",
    status: "in_progress",
    controls: [
      { code: "4", title: "Ethical Considerations", description: "Conduct the clinical investigation in accordance with ethical principles in the Declaration of Helsinki and applicable regulatory requirements; obtain IRB/EC approval and informed consent." },
      { code: "5", title: "Clinical Investigation Planning", description: "Plan the clinical investigation including risk assessment, justification for the design, primary/secondary endpoints, statistical considerations and a Clinical Investigation Plan (CIP)." },
      { code: "6.1", title: "Conduct — Site Selection and Initiation", description: "Select investigation sites with adequate facilities, qualified investigators and trained staff; perform site initiation and document training records." },
      { code: "6.4", title: "Conduct — Adverse Event Recording and Reporting", description: "Record all adverse events (AE), serious adverse events (SAE) and device deficiencies; report to sponsor, EC and regulatory authority within required timelines." },
      { code: "7", title: "Suspension, Termination and Completion", description: "Define and document procedures for suspension, premature termination and normal completion of the clinical investigation." },
      { code: "8", title: "Sponsor Responsibilities", description: "Sponsor must establish QMS for the clinical investigation, monitor the investigation, manage data integrity, retain essential documents and report to regulatory authorities." },
      { code: "9", title: "Investigator Responsibilities", description: "Investigators must conduct the investigation in accordance with the CIP, applicable regulatory requirements and ethical principles; obtain consent and report AEs/SAEs." },
      { code: "Annex A", title: "Clinical Investigation Plan Contents", description: "CIP shall include device description, intended purpose, justification for design, risks and benefits, objectives, design, statistical plan, ethics and consent procedures." },
      { code: "Annex B", title: "Investigator's Brochure (IB)", description: "IB shall summarize preclinical and prior clinical data, intended purpose, target population, risks and benefits, and instructions for use." },
      { code: "Annex C", title: "Case Report Forms (CRF) and Source Documents", description: "Define CRF design, source data verification, data correction procedures and audit trail to ensure data integrity." },
      { code: "Annex F", title: "Clinical Investigation Report (CIR)", description: "CIR shall include investigation summary, methodology, results, AE/SAE listings, statistical analysis, deviations from CIP and conclusions on safety/performance." },
    ],
  },
  {
    id: "fw-21cfr-820",
    code: "21 CFR 820",
    name: "FDA 21 CFR Part 820 — Quality System Regulation (QSR)",
    category: "FDA Medical Device",
    status: "in_progress",
    controls: [
      { code: "820.20", title: "Management Responsibility", description: "Establish quality policy, organizational structure, management review and quality system procedures; ensure adequate resources and assign management representative." },
      { code: "820.22", title: "Quality Audit", description: "Conduct quality audits to assure that the quality system is in compliance and to determine the effectiveness of the quality system; document audit dates and results." },
      { code: "820.25", title: "Personnel", description: "Have sufficient personnel with the necessary education, background, training and experience to assure all activities required are correctly performed; document training." },
      { code: "820.30", title: "Design Controls", description: "Establish design control procedures: design and development planning, design input, design output, design review, design verification, design validation, design transfer, design changes and design history file (DHF)." },
      { code: "820.40", title: "Document Controls", description: "Establish procedures to control all documents: approval before issue, distribution, review/update, identification of obsolete documents and document changes." },
      { code: "820.50", title: "Purchasing Controls", description: "Establish procedures to ensure that all purchased or otherwise received product and services conform to specified requirements; evaluate and select suppliers." },
      { code: "820.65", title: "Traceability", description: "For devices intended for surgical implant or supporting/sustaining life, establish procedures for identifying with a control number each unit, lot or batch." },
      { code: "820.70", title: "Production and Process Controls", description: "Develop, conduct, control and monitor production processes to ensure a device conforms to its specifications, including process validation where appropriate." },
      { code: "820.75", title: "Process Validation", description: "Where the results of a process cannot be fully verified by subsequent inspection and test, the process shall be validated with a high degree of assurance and approved." },
      { code: "820.90", title: "Nonconforming Product", description: "Establish procedures to control product that does not conform to specified requirements: identification, documentation, evaluation, segregation, disposition." },
      { code: "820.100", title: "Corrective and Preventive Action (CAPA)", description: "Establish procedures for: analyzing data sources, investigating cause of nonconformities, identifying actions, verifying effectiveness, implementing changes and disseminating information." },
      { code: "820.180", title: "Records — General Requirements", description: "All records required by this part shall be maintained at the manufacturing establishment or other location reasonably accessible to FDA; retention per device life or 2 years from release, whichever is longer." },
      { code: "820.184", title: "Device History Record (DHR)", description: "Maintain DHRs demonstrating that each device is manufactured in accordance with the DMR; include dates, quantity, acceptance records, primary identification label and UDI/UPC." },
      { code: "820.186", title: "Quality System Record (QSR)", description: "Establish and maintain a quality system record (QSR) including procedures and documentation of activities required by Part 820 not specific to a particular type of device." },
      { code: "820.198", title: "Complaint Files", description: "Designate a formally designated unit to receive, review and evaluate complaints; establish procedures for uniform/timely handling, reportable-event determination and MDR." },
    ],
  },
  {
    id: "fw-21cfr-807",
    code: "21 CFR 807",
    name: "FDA 21 CFR Part 807 — Establishment Registration, Device Listing & 510(k) Premarket Notification",
    category: "FDA Medical Device",
    status: "in_progress",
    controls: [
      { code: "807.20", title: "Who Must Register and Submit a Device List", description: "Owners or operators of establishments engaged in manufacture, preparation, propagation, compounding, assembly or processing of a device must register and list devices." },
      { code: "807.22", title: "Times for Registration", description: "Establishments must register within 30 days of beginning operations; foreign establishments must register before exporting devices to the U.S." },
      { code: "807.25", title: "Information Required for Registration and Listing", description: "Provide owner/operator information, U.S. agent (for foreign establishments), establishment activities and a complete device listing for each device." },
      { code: "807.26", title: "Amendments to Registration", description: "Amend registration to reflect changes in name, address, U.S. agent or activities within 30 days of the change." },
      { code: "807.81", title: "When a 510(k) is Required", description: "A 510(k) premarket notification is required at least 90 days before introducing a device into commercial distribution; for any change or modification that could significantly affect safety/effectiveness; or for major change in intended use." },
      { code: "807.87", title: "Information Required in a 510(k)", description: "510(k) must contain: device name, classification, performance standards, proposed labeling, substantial equivalence comparison, financial certification, indications for use." },
      { code: "807.92", title: "Content and Format of a 510(k) Summary", description: "510(k) summary must include submitter information, device names, predicate device, description of device, intended use, technological characteristics, performance data and SE conclusion." },
      { code: "807.93", title: "Content and Format of a 510(k) Statement", description: "Alternative to 510(k) summary; certifies that safety/effectiveness information will be made available within 30 days of request." },
      { code: "807.94", title: "Truthful and Accurate Statement", description: "Each 510(k) must contain a truthful and accurate statement signed by the submitter affirming all information is truthful, accurate and not misleading." },
      { code: "807.97", title: "Misbranding by Reference to Premarket Notification", description: "Reference to receipt of a 510(k) order does not in any way denote official approval of the device; misuse of FDA clearance in labeling is misbranding." },
    ],
  },
  {
    id: "fw-21cfr-814",
    code: "21 CFR 814",
    name: "FDA 21 CFR Part 814 — Premarket Approval (PMA) of Medical Devices",
    category: "FDA Medical Device",
    status: "in_progress",
    controls: [
      { code: "814.20", title: "Application Content (PMA)", description: "PMA must contain: indications for use, device description, alternative practices, marketing history, summary of studies, technical sections (nonclinical lab and clinical), bibliography, samples, labeling, environmental assessment and financial certification." },
      { code: "814.37", title: "PMA Amendments and Resubmitted PMAs", description: "Amendments may be submitted on the applicant's initiative or in response to FDA request; FDA may consider an amendment as a major amendment that extends the review clock." },
      { code: "814.39", title: "PMA Supplements", description: "Submit a PMA supplement for any change affecting safety or effectiveness, including new indications, labeling changes, manufacturing changes or design modifications." },
      { code: "814.42", title: "Filing a PMA", description: "FDA has 45 days to determine whether the PMA may be filed; deficiencies that prevent filing must be communicated in a Refuse-to-File letter." },
      { code: "814.44", title: "Procedures for Review of a PMA", description: "FDA review includes substantive review, advisory committee review (if needed), inspection of manufacturing facility and labeling review; may issue Approvable, Not Approvable or Denial letters." },
      { code: "814.45", title: "Denial of Approval of a PMA", description: "FDA may deny approval if there is a lack of valid scientific evidence, the device is not safe/effective, manufacturing facilities/methods do not conform to QSR, or labeling is false/misleading." },
      { code: "814.80", title: "General Postapproval Requirements", description: "After PMA approval, applicant must continue to comply with conditions of approval, postapproval requirements specified in the order and applicable parts of QSR." },
      { code: "814.82", title: "Postapproval Requirements (Specific)", description: "FDA may impose postapproval requirements including restrictions on sale/distribution, postapproval studies, periodic reports, MDR reporting and labeling restrictions." },
      { code: "814.84", title: "Reports", description: "Periodic reports must contain identification of changes not requiring a supplement, summary of complaints, MDR-reportable events and any other information specified in the approval order." },
      { code: "814.116", title: "Procedures for Review of an HDE Application", description: "FDA review procedures for Humanitarian Device Exemption (HDE) applications under Subpart H — devices for rare disease/condition (≤8,000 patients/yr in U.S.); requires demonstration of probable benefit, no comparable device and IRB approval at user facility." },
    ],
  },
  {
    id: "fw-eu-mdr-2017-745",
    code: "MDR 2017/745",
    name: "EU Medical Device Regulation 2017/745 (MDR)",
    category: "EU Medical Device",
    status: "in_progress",
    controls: [
      { code: "Art. 10", title: "General Obligations of Manufacturers", description: "Manufacturers shall ensure devices comply with GSPR, establish a QMS, maintain technical documentation, perform conformity assessment, draw up an EU declaration of conformity and affix CE marking." },
      { code: "Art. 15", title: "Person Responsible for Regulatory Compliance (PRRC)", description: "Manufacturers shall have available within their organisation at least one person responsible for regulatory compliance with appropriate qualifications." },
      { code: "Art. 18", title: "Implant Card and Information for Implantable Devices", description: "For implantable devices, manufacturers shall supply an implant card and information enabling identification of the device, warnings and expected lifetime." },
      { code: "Art. 19", title: "EU Declaration of Conformity", description: "Manufacturers shall draw up the EU declaration of conformity stating that the device meets the requirements of MDR; keep up to date for at least 10 years after last device placed on market." },
      { code: "Art. 27", title: "Unique Device Identification (UDI)", description: "Affix a UDI carrier on the device label and packaging; submit UDI data to the EUDAMED UDI database before placing on the market." },
      { code: "Art. 51", title: "Classification of Devices", description: "Devices shall be divided into Classes I, IIa, IIb and III taking into account intended purpose and risks per the classification rules in Annex VIII." },
      { code: "Art. 52", title: "Conformity Assessment Procedures", description: "Manufacturers shall undergo a conformity assessment procedure (Annex IX, X or XI) appropriate to the device class, with notified body involvement for Class IIa, IIb and III." },
      { code: "Art. 61", title: "Clinical Evaluation", description: "Confirmation of conformity with relevant GSPR shall be based on clinical data providing sufficient clinical evidence; documented in a Clinical Evaluation Report (CER)." },
      { code: "Art. 83", title: "Post-Market Surveillance System", description: "Plan, establish, document, implement, maintain and update a PMS system proportionate to the risk class and appropriate for the type of device, including a PMS plan and PSUR/PMS report." },
      { code: "Art. 87", title: "Reporting of Serious Incidents and Field Safety Corrective Actions", description: "Report serious incidents to competent authorities (immediately, no later than 15 days; 2 days for serious public health threat; 10 days for death/unanticipated serious deterioration); report FSCAs." },
      { code: "Annex I", title: "General Safety and Performance Requirements (GSPR)", description: "Devices shall achieve the performance intended and be safe; design and manufacture shall reduce risks as far as possible; address chemical, physical, biological and electrical hazards." },
      { code: "Annex II", title: "Technical Documentation", description: "Technical documentation shall include device description, information to be supplied by the manufacturer, design and manufacturing information, GSPR conformity, benefit-risk analysis and product verification/validation." },
      { code: "Annex III", title: "Technical Documentation on Post-Market Surveillance", description: "Manufacturer shall prepare PMS plan, PSUR (Class IIa, IIb, III), PMS report (Class I) and trend reports per Article 88." },
      { code: "Annex XIV", title: "Clinical Evaluation and Post-Market Clinical Follow-Up (PMCF)", description: "Define clinical evaluation methodology including PMCF plan and PMCF evaluation report integrated into the CER." },
    ],
  },
  {
    id: "fw-eu-ivdr-2017-746",
    code: "IVDR 2017/746",
    name: "EU In Vitro Diagnostic Regulation 2017/746 (IVDR)",
    category: "EU Medical Device",
    status: "in_progress",
    controls: [
      { code: "Art. 5", title: "Placing on the Market and Putting into Service", description: "An IVD may only be placed on the market or put into service if it complies with the IVDR when duly supplied and properly installed, maintained and used in accordance with its intended purpose." },
      { code: "Art. 10", title: "General Obligations of Manufacturers", description: "Establish risk management system, perform performance evaluation, draw up technical documentation, undertake conformity assessment, establish PMS and PMPF systems and have appropriate financial coverage." },
      { code: "Art. 15", title: "Person Responsible for Regulatory Compliance (PRRC)", description: "IVD manufacturers shall have at least one person responsible for regulatory compliance with required qualifications and at least one year of experience in IVD regulatory affairs/QMS." },
      { code: "Art. 24", title: "Unique Device Identification (UDI)", description: "Assign a Basic UDI-DI and UDI-DI to each IVD; submit UDI data to EUDAMED before placing on market." },
      { code: "Art. 47", title: "Classification of IVDs", description: "IVDs shall be classified into Classes A, B, C and D based on intended purpose and inherent risk per the classification rules in Annex VIII." },
      { code: "Art. 48", title: "Conformity Assessment Procedures", description: "Apply conformity assessment procedure appropriate to the class: self-declaration (Class A non-sterile) or notified body involvement (Class A sterile, B, C, D)." },
      { code: "Art. 56", title: "Performance Evaluation and Clinical Evidence", description: "Conduct performance evaluation according to a performance evaluation plan; demonstrate scientific validity, analytical performance and clinical performance; document in a Performance Evaluation Report (PER)." },
      { code: "Art. 78", title: "Performance Studies — General Requirements", description: "Performance studies, including those involving patient samples, shall be designed and conducted to ensure rights/safety/dignity/well-being of subjects and reliability of generated data." },
      { code: "Art. 83", title: "Post-Market Surveillance System", description: "Plan, establish, document, implement, maintain and update a proportionate PMS system; produce PMS plan and PSUR (Class C, D) or PMS report (Class A, B)." },
      { code: "Art. 84", title: "Post-Market Performance Follow-Up (PMPF)", description: "Conduct PMPF as continuous process that updates the performance evaluation; document in PMPF plan and PMPF evaluation report integrated into the PER." },
      { code: "Annex I", title: "General Safety and Performance Requirements (GSPR)", description: "IVDs shall achieve their intended performance; design and manufacture shall ensure suitability for analytical and clinical performance; address chemical, biological and informational hazards." },
      { code: "Annex II", title: "Technical Documentation", description: "Technical documentation shall include device description, design and manufacturing information, GSPR conformity, benefit-risk analysis, product verification/validation and information supplied by manufacturer." },
      { code: "Annex IX", title: "Conformity Assessment Based on a Quality Management System", description: "Notified body audit of full QMS covering design, manufacture, final inspection and testing; surveillance audits and assessment of technical documentation per device class." },
    ],
  },
];

export async function bootstrapFrameworks(): Promise<void> {
  try {
    for (const fw of FRAMEWORKS) {
      await pool.query(
        `INSERT INTO compliance_frameworks (id, code, name, category, status, score, controls_total, last_audit_at)
         VALUES ($1,$2,$3,$4,$5,$6,$7, NOW())
         ON CONFLICT (id) DO UPDATE SET
           code = EXCLUDED.code,
           name = EXCLUDED.name,
           category = EXCLUDED.category,
           controls_total = EXCLUDED.controls_total`,
        [fw.id, fw.code, fw.name, fw.category, fw.status, 0, fw.controls.length],
      );
      let inserted = 0;
      for (const c of fw.controls) {
        const id = `${fw.id}-${c.code.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`;
        const res = await pool.query(
          `INSERT INTO compliance_controls (id, framework_id, code, title, description, status, owner, evidence_count)
           VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
           ON CONFLICT (id) DO UPDATE SET
             code = EXCLUDED.code,
             title = EXCLUDED.title,
             description = EXCLUDED.description`,
          [id, fw.id, c.code, c.title, c.description, "not_assessed", "Unassigned", 0],
        );
        if (res.rowCount && res.rowCount > 0) inserted++;
      }
      if (inserted > 0) {
        logger.info({ framework: fw.code, inserted }, "Bootstrapped framework controls");
      }
    }
  } catch (err) {
    logger.warn({ err }, "Framework bootstrap failed (continuing startup)");
  }
}
