import PizZip from "pizzip";
import Docxtemplater from "docxtemplater";
import { Document, Packer, Paragraph, HeadingLevel, TextRun, AlignmentType, PageBreak, Header, Footer, PageNumber } from "docx";
import { db, workspaceTemplatesTable, type ReportContent } from "@workspace/db";
import { eq } from "drizzle-orm";

export interface RenderableReport {
  /** Report name shown in the picker (e.g. "Functional Safety Plan").
   *  Used as the default {title} placeholder value, with any
   *  "Auditee Report: " / "Auditee — " style prefix stripped. */
  title: string;
  /** Optional subtitle override. If absent we fall back to the project
   *  name (so {subtitle} = the project the report is for, by default). */
  subtitle?: string | null;
  tone: string;
  updatedAt: Date | string;
  content: ReportContent;
  /** Project this report belongs to. Used as the default {subtitle}
   *  when the report doesn't carry an explicit subtitle. */
  projectName?: string | null;
  /** Workspace plan tier — controls the {generated_by} placeholder.
   *  Free plans always render "Auditee". Paid plans (anything other
   *  than `free`) render an empty string so the customer's branded
   *  document can drop the "generated by Auditee" footer line. */
  workspacePlan?: string | null;
}

interface TemplateData {
  title: string;
  subtitle: string;
  date: string;
  tone: string;
  generated_by: string;
  executive_summary: string;
  sections: { heading: string; body: string; citations: string }[];
  evidence: { id: string; label: string; source: string }[];
}

/**
 * Strip any "Auditee Report: ", "Auditee — ", "Auditee Report — " etc.
 * prefix from a report title so the {title} placeholder is just the
 * report name the user actually picked (e.g. "Functional Safety Plan"
 * instead of "Auditee Report: Functional Safety Plan"). Customer-branded
 * documents must not advertise the upstream tool in their cover page.
 */
function stripAuditeePrefix(title: string): string {
  return title
    .replace(/^\s*auditee(\s+report)?\s*[:\-—–|]\s*/i, "")
    .replace(/^\s*auditee\s+/i, "")
    .trim() || title;
}

function isPaidPlan(plan: string | null | undefined): boolean {
  if (!plan) return false;
  const t = plan.toLowerCase();
  return t !== "free" && t !== "trial";
}

function toTemplateData(report: RenderableReport): TemplateData {
  const c = report.content;
  // Title default = the picked report name (no "Auditee Report:" prefix).
  // Subtitle default = the picked project name. report.content.subtitle
  // wins if explicitly set on the AI-generated content.
  const titleSource = c.title || report.title;
  const title = stripAuditeePrefix(titleSource);
  const subtitle = c.subtitle ?? report.subtitle ?? report.projectName ?? "";
  return {
    title,
    subtitle,
    date: new Date(report.updatedAt).toISOString().split("T")[0]!,
    tone: report.tone,
    generated_by: isPaidPlan(report.workspacePlan) ? "" : "Auditee",
    executive_summary: c.executiveSummary,
    sections: c.sections.map((s) => ({
      heading: s.heading,
      body: s.body,
      citations: s.citations?.length ? s.citations.join(", ") : "",
    })),
    evidence: c.evidence.slice(0, 200).map((e) => ({
      id: e.id,
      label: e.label,
      source: e.source,
    })),
  };
}

/**
 * Render a report through the workspace's company template.
 *
 * Returns the rendered .docx buffer if a template exists for the workspace,
 * or null if there is no template (caller should fall back to the standard
 * builder).
 *
 * Throws if the template exists but is malformed — surfaced to the user as
 * a 500 with a clear message so they can fix their template.
 *
 * Header / footer preservation: the customer's uploaded letterhead can
 * contain branded headers and footers (logo, page numbers, address line,
 * confidentiality notice). Those XML parts are snapshotted before render
 * and restored verbatim afterwards, so docxtemplater's placeholder pass
 * NEVER touches them — even if they happen to contain {curly} text the
 * user added for their own purposes.
 */
export async function renderWithCompanyTemplate(
  workspaceId: string,
  report: RenderableReport,
): Promise<Buffer | null> {
  const [tpl] = await db
    .select()
    .from(workspaceTemplatesTable)
    .where(eq(workspaceTemplatesTable.workspaceId, workspaceId));
  if (!tpl) return null;

  const zip = new PizZip(tpl.fileBytes);

  // Snapshot every header/footer part BEFORE docxtemplater runs so we
  // can restore them byte-for-byte after render. PizZip part names are
  // POSIX-style: word/header1.xml, word/footer2.xml, etc.
  const preservedParts = new Map<string, string>();
  for (const fileName of Object.keys(zip.files)) {
    if (/^word\/(header|footer)\d*\.xml$/i.test(fileName)) {
      const file = zip.file(fileName);
      if (file) preservedParts.set(fileName, file.asText());
    }
  }

  const doc = new Docxtemplater(zip, {
    paragraphLoop: true,
    linebreaks: true,
    delimiters: { start: "{", end: "}" },
    nullGetter: () => "",
  });

  doc.render(toTemplateData(report));

  // Restore the original header/footer XML parts on the post-render zip
  // so the user's letterhead survives untouched.
  const outZip = doc.getZip();
  for (const [fileName, originalXml] of preservedParts) {
    outZip.file(fileName, originalXml);
  }

  return outZip.generate({ type: "nodebuffer", compression: "DEFLATE" }) as Buffer;
}

/**
 * Build a sample company template that users can download, edit in Word, and
 * re-upload. The sample contains a header with company name placeholder, a
 * footer with page numbers, a cover page, and the standard placeholders that
 * the export pipeline understands.
 *
 * NOTE: We can't include a logo image here — the user is expected to open the
 * sample in Word and paste their own logo into the header.
 */
export async function buildSampleTemplate(): Promise<Buffer> {
  const header = new Header({
    children: [
      new Paragraph({
        alignment: AlignmentType.RIGHT,
        children: [
          new TextRun({
            text: "[Replace with your company logo / name]",
            italics: true,
            color: "94A3B8",
            size: 18,
          }),
        ],
      }),
    ],
  });

  // Footer intentionally does NOT include {generated_by} — that placeholder
  // is plan-dependent (empty for paid plans) and we don't want a customer's
  // branded footer to read "Confidential —  " on paid plans. Users can drop
  // {generated_by} into the footer themselves on free plans if they want to.
  // Note: header/footer XML in *uploaded* templates is preserved verbatim
  // by renderWithCompanyTemplate() — only the body gets placeholder
  // substitution. So this footer is just for the sample.
  const footer = new Footer({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({ text: "Page ", color: "64748B", size: 18 }),
          new TextRun({ children: [PageNumber.CURRENT], color: "64748B", size: 18 }),
          new TextRun({ text: " of ", color: "64748B", size: 18 }),
          new TextRun({ children: [PageNumber.TOTAL_PAGES], color: "64748B", size: 18 }),
          new TextRun({
            text: "  ·  Confidential",
            color: "94A3B8",
            size: 18,
          }),
        ],
      }),
    ],
  });

  const body: Paragraph[] = [
    // Cover page
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 2400 },
      children: [new TextRun({ text: "{title}", bold: true, size: 56 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 240 },
      children: [new TextRun({ text: "{subtitle}", italics: true, size: 28, color: "475569" })],
    }),
    // Optional metadata line — users can delete this whole paragraph if
    // they want a cleaner cover page. {date} is plain text so an empty
    // template (or a paid-plan workspace that nuked the line) shows
    // nothing rather than a stray label.
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 720 },
      children: [
        new TextRun({ text: "Audience tone: ", color: "64748B" }),
        new TextRun({ text: "{tone}", bold: true }),
        new TextRun({ text: "    Generated: ", color: "64748B" }),
        new TextRun({ text: "{date}", bold: true }),
      ],
    }),
    new Paragraph({ children: [new PageBreak()] }),

    // Executive summary
    new Paragraph({ text: "Executive Summary", heading: HeadingLevel.HEADING_1 }),
    new Paragraph({ children: [new TextRun("{executive_summary}")] }),

    // Sections loop — docxtemplater will repeat everything between
    // {#sections} and {/sections} once per section.
    new Paragraph({ children: [new TextRun("{#sections}")] }),
    new Paragraph({ text: "{heading}", heading: HeadingLevel.HEADING_1 }),
    new Paragraph({ children: [new TextRun("{body}")] }),
    new Paragraph({
      children: [
        new TextRun({ text: "Evidence: ", bold: true, color: "64748B" }),
        new TextRun({ text: "{citations}", color: "64748B" }),
      ],
    }),
    new Paragraph({ children: [new TextRun("{/sections}")] }),

    // Evidence index
    new Paragraph({ text: "Evidence Index", heading: HeadingLevel.HEADING_1 }),
    new Paragraph({ children: [new TextRun("{#evidence}")] }),
    new Paragraph({
      children: [
        new TextRun({ text: "{id}", bold: true }),
        new TextRun({ text: " — {label} ({source})" }),
      ],
    }),
    new Paragraph({ children: [new TextRun("{/evidence}")] }),
  ];

  const doc = new Document({
    creator: "Auditee",
    title: "Auditee Company Template — Sample",
    description:
      "Edit in Word: replace the header text with your logo, adjust styles/fonts/margins, " +
      "then upload via Settings → Company Template. Keep the {placeholders} intact.",
    sections: [
      {
        properties: {},
        headers: { default: header },
        footers: { default: footer },
        children: body,
      },
    ],
  });

  return await Packer.toBuffer(doc);
}
