import PizZip from "pizzip";
import Docxtemplater from "docxtemplater";
import { Document, Packer, Paragraph, HeadingLevel, TextRun, AlignmentType, PageBreak, Header, Footer, PageNumber } from "docx";
import { db, workspaceTemplatesTable, type ReportContent } from "@workspace/db";
import { eq } from "drizzle-orm";

export interface RenderableReport {
  title: string;
  subtitle?: string | null;
  tone: string;
  updatedAt: Date | string;
  content: ReportContent;
}

interface TemplateData {
  title: string;
  subtitle: string;
  date: string;
  tone: string;
  generated_by: string;
  executive_summary: string;
  sections: { heading: string; body: string; citations: string }[];
  evidence: { id: string; label: string; source: string }[];
}

function toTemplateData(report: RenderableReport): TemplateData {
  const c = report.content;
  return {
    title: c.title,
    subtitle: c.subtitle ?? "",
    date: new Date(report.updatedAt).toISOString().split("T")[0]!,
    tone: report.tone,
    generated_by: "Auditee",
    executive_summary: c.executiveSummary,
    sections: c.sections.map((s) => ({
      heading: s.heading,
      body: s.body,
      citations: s.citations?.length ? s.citations.join(", ") : "",
    })),
    evidence: c.evidence.slice(0, 200).map((e) => ({
      id: e.id,
      label: e.label,
      source: e.source,
    })),
  };
}

/**
 * Render a report through the workspace's company template.
 *
 * Returns the rendered .docx buffer if a template exists for the workspace,
 * or null if there is no template (caller should fall back to the standard
 * builder).
 *
 * Throws if the template exists but is malformed — surfaced to the user as
 * a 500 with a clear message so they can fix their template.
 */
export async function renderWithCompanyTemplate(
  workspaceId: string,
  report: RenderableReport,
): Promise<Buffer | null> {
  const [tpl] = await db
    .select()
    .from(workspaceTemplatesTable)
    .where(eq(workspaceTemplatesTable.workspaceId, workspaceId));
  if (!tpl) return null;

  const zip = new PizZip(tpl.fileBytes);
  const doc = new Docxtemplater(zip, {
    paragraphLoop: true,
    linebreaks: true,
    delimiters: { start: "{", end: "}" },
    nullGetter: () => "",
  });

  doc.render(toTemplateData(report));

  return doc.getZip().generate({ type: "nodebuffer", compression: "DEFLATE" }) as Buffer;
}

/**
 * Build a sample company template that users can download, edit in Word, and
 * re-upload. The sample contains a header with company name placeholder, a
 * footer with page numbers, a cover page, and the standard placeholders that
 * the export pipeline understands.
 *
 * NOTE: We can't include a logo image here — the user is expected to open the
 * sample in Word and paste their own logo into the header.
 */
export async function buildSampleTemplate(): Promise<Buffer> {
  const header = new Header({
    children: [
      new Paragraph({
        alignment: AlignmentType.RIGHT,
        children: [
          new TextRun({
            text: "[Replace with your company logo / name]",
            italics: true,
            color: "94A3B8",
            size: 18,
          }),
        ],
      }),
    ],
  });

  const footer = new Footer({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({ text: "Page ", color: "64748B", size: 18 }),
          new TextRun({ children: [PageNumber.CURRENT], color: "64748B", size: 18 }),
          new TextRun({ text: " of ", color: "64748B", size: 18 }),
          new TextRun({ children: [PageNumber.TOTAL_PAGES], color: "64748B", size: 18 }),
          new TextRun({
            text: "  ·  Confidential — generated by {generated_by}",
            color: "94A3B8",
            size: 18,
          }),
        ],
      }),
    ],
  });

  const body: Paragraph[] = [
    // Cover page
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 2400 },
      children: [new TextRun({ text: "{title}", bold: true, size: 56 })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 240 },
      children: [new TextRun({ text: "{subtitle}", italics: true, size: 28, color: "475569" })],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { before: 720 },
      children: [
        new TextRun({ text: "Generated: ", color: "64748B" }),
        new TextRun({ text: "{date}", bold: true }),
        new TextRun({ text: "    Audience tone: ", color: "64748B" }),
        new TextRun({ text: "{tone}", bold: true }),
      ],
    }),
    new Paragraph({ children: [new PageBreak()] }),

    // Executive summary
    new Paragraph({ text: "Executive Summary", heading: HeadingLevel.HEADING_1 }),
    new Paragraph({ children: [new TextRun("{executive_summary}")] }),

    // Sections loop — docxtemplater will repeat everything between
    // {#sections} and {/sections} once per section.
    new Paragraph({ children: [new TextRun("{#sections}")] }),
    new Paragraph({ text: "{heading}", heading: HeadingLevel.HEADING_1 }),
    new Paragraph({ children: [new TextRun("{body}")] }),
    new Paragraph({
      children: [
        new TextRun({ text: "Evidence: ", bold: true, color: "64748B" }),
        new TextRun({ text: "{citations}", color: "64748B" }),
      ],
    }),
    new Paragraph({ children: [new TextRun("{/sections}")] }),

    // Evidence index
    new Paragraph({ text: "Evidence Index", heading: HeadingLevel.HEADING_1 }),
    new Paragraph({ children: [new TextRun("{#evidence}")] }),
    new Paragraph({
      children: [
        new TextRun({ text: "{id}", bold: true }),
        new TextRun({ text: " — {label} ({source})" }),
      ],
    }),
    new Paragraph({ children: [new TextRun("{/evidence}")] }),
  ];

  const doc = new Document({
    creator: "Auditee",
    title: "Auditee Company Template — Sample",
    description:
      "Edit in Word: replace the header text with your logo, adjust styles/fonts/margins, " +
      "then upload via Settings → Company Template. Keep the {placeholders} intact.",
    sections: [
      {
        properties: {},
        headers: { default: header },
        footers: { default: footer },
        children: body,
      },
    ],
  });

  return await Packer.toBuffer(doc);
}
