import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import requirementsRouter from "./requirements";
import traceabilityRouter from "./traceability";
import codeArtifactsRouter from "./codeArtifacts";
import complianceRouter from "./compliance";
import dashboardRouter from "./dashboard";
import activityRouter from "./activity";
import pdlcRouter from "./pdlc";
import legacyRouter from "./legacy";
import demoRequestsRouter from "./demoRequests";
import aiRouter from "./ai";
import commentsRouter from "./comments";
import capaRouter from "./capa";
import reportsRouter from "./reports";
import repoPushRouter from "./repoPush";
import workflowsRouter from "./workflows";
import notificationsRouter from "./notifications";
import recurringAuditsRouter from "./recurringAudits";
import analyticsRouter from "./analytics";
import sourcesRouter from "./sources";
import defectsRouter from "./defects";
import workspaceRouter from "./workspace";
import workspaceTemplateRouter from "./workspaceTemplate";
import testCasesRouter from "./testCases";
import leadsRouter from "./leads";
import billingRouter from "./billing";
import customStandardsRouter from "./customStandards";
import gdprRouter from "./gdpr";
import tutorialTtsRouter from "./tutorialTts";
import ssoRouter from "./sso";
import oidcRouter from "./oidc";
import scimRouter from "./scim";
import enterpriseRouter from "./enterprise";
import enterpriseExtraRouter from "./enterpriseExtra";

const router: IRouter = Router();

router.use(healthRouter);
router.use(projectsRouter);
router.use(requirementsRouter);
router.use(traceabilityRouter);
router.use(codeArtifactsRouter);
router.use(complianceRouter);
router.use(dashboardRouter);
router.use(activityRouter);
router.use(pdlcRouter);
router.use(legacyRouter);
router.use(demoRequestsRouter);
router.use(aiRouter);
router.use(commentsRouter);
router.use(capaRouter);
router.use(reportsRouter);
router.use(repoPushRouter);
router.use(workflowsRouter);
router.use(notificationsRouter);
router.use(recurringAuditsRouter);
router.use(analyticsRouter);
router.use(sourcesRouter);
router.use(defectsRouter);
router.use(workspaceRouter);
router.use(workspaceTemplateRouter);
router.use(testCasesRouter);
router.use(leadsRouter);
router.use(billingRouter);
router.use(customStandardsRouter);
router.use(gdprRouter);
router.use(tutorialTtsRouter);
router.use(ssoRouter);
router.use(oidcRouter);
router.use(scimRouter);
router.use(enterpriseRouter);
router.use(enterpriseExtraRouter);

export default router;
